#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "Mercado Pago — assinatura PROFISSIONAL (produção)"

# Production values land in the working env file (reference) AND must be pasted
# into the Vercel project environment variables (Stage 4).
ENV_FILE="${ENV_FILE:-.env.local}"
PROD_URL="https://agendify-liart.vercel.app"

# ── Stage 1: confirmar URL de produção + ligação do repo ───────────────────
stage "Produção: URL e ligação do repo"
say "Confirma a URL de produção e que o projeto Vercel está ligado ao repo."
step "URL de produção esperada: $PROD_URL"
step "Confirme no painel da Vercel que o projeto está ligado a https://github.com/DiovannyMartins/agendify"
note "Deploy acontece ao fazer push na main (integração GitHub) ou via 'vercel deploy'."
confirm "A URL de produção é $PROD_URL e o repo está ligado à Vercel?" || { warn "Ajuste PROD_URL no script ou corrija a ligação e rode de novo."; }
write_env APP_URL "$PROD_URL"
write_env MERCADO_PAGO_NOTIFICATION_URL "$PROD_URL/api/webhooks/mercadopago"

# ── Stage 2: ativar credenciais de produção (Mercado Pago) ────────────────
stage "Mercado Pago: credenciais de produção"
say "Ativa as credenciais de produção e copia o Access Token (APP_USR-*)."
open_url "https://www.mercadopago.com.br/developers/panel/app"
step "Abra a aplicação da integração de assinaturas (Subscriptions / preapproval)."
step "Em 'Produção', clique em 'Ativar credenciais de produção' (complete a verificação se solicitado)."
step "Copie o 'Access Token' de produção (começa com APP_USR-)."
warn "O valor atual em $ENV_FILE é o de TESTE (TEST-*). Cole o APP_USR-* — NÃO pressione Enter."
ask_secret MERCADO_PAGO_ACCESS_TOKEN "Cole o Access Token de produção (APP_USR-):"
write_env MERCADO_PAGO_ACCESS_TOKEN "$MERCADO_PAGO_ACCESS_TOKEN"
note "Guardado em $ENV_FILE (server-only, nunca commite). Também será colado na Vercel (Stage 4)."

# ── Stage 3: webhook de produção (Mercado Pago) ───────────────────────────
stage "Mercado Pago: webhook de produção"
say "Registra a URL de notificação de produção e captura a secret."
open_url "https://www.mercadopago.com.br/developers/panel/app"
step "No app, menu 'Webhooks > Configurar notificações'."
step "Em 'URL de produção', cole: $MERCADO_PAGO_NOTIFICATION_URL"
step "Marque o evento 'Planos e assinaturas' → 'Vinculação de aplicações' (subscription_preapproval) e salve."
step "Revele a assinatura (secret) do webhook e copie-a."
warn "O valor atual em $ENV_FILE é a secret de TESTE. Cole a secret de produção — NÃO pressione Enter."
ask_secret MERCADO_PAGO_WEBHOOK_SECRET "Cole a secret do webhook de produção (x-signature):"
write_env MERCADO_PAGO_WEBHOOK_SECRET "$MERCADO_PAGO_WEBHOOK_SECRET"
note "Dica: use o botão 'Simular' para enviar um evento de teste à URL e confirmar a resposta 200."

# ── Stage 4: variáveis na Vercel ──────────────────────────────────────────
stage "Vercel: variáveis de ambiente"
say "Adiciona as 4 variáveis de produção no projeto da Vercel."
open_url "https://vercel.com/dashboard"
step "Abra o projeto (agendify) → Settings → Environment Variables."
note "Cada variável já foi gravada em $ENV_FILE. Cole os valores abaixo (server-side):"
for k in MERCADO_PAGO_ACCESS_TOKEN MERCADO_PAGO_WEBHOOK_SECRET MERCADO_PAGO_NOTIFICATION_URL APP_URL; do
  v=$(_existing "$k" || true)
  printf '  %s= %s\n' "$k" "$v"
done
step "Para cada uma, adicione na Vercel (Production) e clique em 'Save'."
step "Garanta também que NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY e SUPABASE_SERVICE_ROLE_KEY existem na Vercel."
pause "Adicione as variáveis na Vercel e pressione Enter."

# ── Stage 5: URL de produção no Supabase Auth ─────────────────────────────
stage "Supabase Auth: URL de produção"
say "Adiciona a URL de produção nas configurações de Auth (README exige)."
open_url "https://supabase.com/dashboard/project/wgmmrpvrtgsxwdhtgfjy/auth/url-configuration"
step "Em 'Site URL', cole: $PROD_URL"
step "Em 'Redirect URLs', adicione: $PROD_URL/**  e  $PROD_URL/auth/callback"
step "Salve."
pause "Salve as URLs de Auth no Supabase e pressione Enter."

# ── Stage 6: deploy e validação ───────────────────────────────────────────
stage "Deploy e validação"
say "Publica e confirma que o webhook de produção responde."
if confirm "Fazer deploy agora (push na main / vercel deploy)?"; then
  note "Deploy iniciado. Após concluir, valide o endpoint:"
else
  note "Deploy manual. Após publicar, valide o endpoint:"
fi
note "Teste GET (esperado 405, rota só aceita POST):"
note "  curl -i https://agendify-liart.vercel.app/api/webhooks/mercadopago"
note "Teste POST sem assinatura (esperado 503/401, fail-closed):"
note "  curl -i -X POST https://agendify-liart.vercel.app/api/webhooks/mercadopago?data.id=x -H 'Content-Type: application/json' -d '{\"type\":\"preapproval\",\"data\":{\"id\":\"x\"}}'"
note "Depois, faça o upgrade real no dashboard (Plano → Fazer upgrade) para validar o ciclo completo."

finish
