-- Migration 0005: updated_at trigger and transactional booking persistence function
-- §20.4 step 5. The booking RPC is the recommended server-only entry point (§11.4).

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_updated_at_profiles
  before update on public.profiles
  for each row execute function public.set_updated_at();

create trigger set_updated_at_businesses
  before update on public.businesses
  for each row execute function public.set_updated_at();

create trigger set_updated_at_services
  before update on public.services
  for each row execute function public.set_updated_at();

create trigger set_updated_at_customers
  before update on public.customers
  for each row execute function public.set_updated_at();

create trigger set_updated_at_bookings
  before update on public.bookings
  for each row execute function public.set_updated_at();

-- §11.4: atomic customer + booking persistence. Server-only RPC.
-- Receives already-validated input; never trusts price/duration/end_at from the client.
create or replace function public.create_booking(
  p_business_id uuid,
  p_service_id uuid,
  p_start_at timestamptz,
  p_customer_name text,
  p_customer_phone text,
  p_customer_email text default null,
  p_customer_note text default null
)
returns public.bookings
language plpgsql
security definer
as $$
declare
  v_service public.services;
  v_customer public.customers;
  v_booking public.bookings;
begin
  -- Re-read the active service and recompute duration/price server-side.
  select * into v_service
  from public.services
  where id = p_service_id and is_active = true;

  if v_service is null then
    raise exception 'SERVICE_NOT_FOUND';
  end if;

  -- Upsert customer by (business_id, phone).
  insert into public.customers (business_id, name, phone, email)
  values (p_business_id, p_customer_name, p_customer_phone, p_customer_email)
  on conflict (business_id, phone)
  do update set name = excluded.name, email = coalesce(excluded.email, public.customers.email)
  returning * into v_customer;

  -- Insert booking with snapshots. public_code is generated by the column default.
  insert into public.bookings (
    business_id,
    service_id,
    customer_id,
    customer_name_snapshot,
    customer_phone_snapshot,
    customer_email_snapshot,
    service_name_snapshot,
    duration_minutes_snapshot,
    price_cents_snapshot,
    start_at,
    end_at,
    customer_note
  )
  values (
    p_business_id,
    v_service.id,
    v_customer.id,
    p_customer_name,
    p_customer_phone,
    p_customer_email,
    v_service.name,
    v_service.duration_minutes,
    v_service.price_cents,
    p_start_at,
    p_start_at + make_interval(mins => v_service.duration_minutes),
    p_customer_note
  )
  returning * into v_booking;

  return v_booking;
end;
$$;
